#%RAML 0.8
title: Weather_REST_API
version: 1.0
baseUri: http://server/api/{version}
/GetCitiesByCountry:
  displayName: Weather Information
  get:
    description: This is used to get Weather Information based on City Name and Country Name
    queryParameters:
      countryName:
    responses:
      200:
        body:
          application/json:
            example: |
                {
                "cityinfo": [
                  {
                    "Country": "Australia",
                    "City": "Brisbane Airport M. O"
                  },
                  {
                    "Country": "Australia",
                    "City": "Cairns Airport"
                  },
                  {
                    "Country": "Australia",
                     "City": "Gladstone"
                  }
                ]
                }
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "id": "http://jsonschema.net",
                "type": "object",
                "properties": {
                "cityinfo": {
                "id": "http://jsonschema.net/weather",
                "type": "object",
                "properties": {
                "id": {
                "Country": "http://jsonschema.net/weather/Country",
                "type": "string"
                },
                "type": {
                "City": "http://jsonschema.net/weather/City",
                "type": "string"
                }
                },
                "required": [
                "id",
                "type"
                ]
                }
                },
                "required": [
                "cityinfo"
                ]
                }
/GetWeather:
 displayName: Get Weather Information Based on City and Country
 get:
    description: This is used to get Weather Information based on City Name and Country Name
    queryParameters:
      countryName:
      cityName:
    responses:
      200:
        body:
          application/json:
            example: |
                {
                  "Location":"Melbourne",
                  "Time":"AM",
                  "Wind":"15 km per hour",
                  "Visibility":"10 KM",
                  "SkyConditions" : "sunny",
                  "Temperature" : "18",
                  "DewPoint" : "2 C",
                  "RelativeHumidity" : "35",
                  "Status" : "Normal"
                }
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "id": "http://jsonschema.net",
                "type": "object",
                "properties": {
                "cityinfo": {
                "id": "http://jsonschema.net/getweather",
                "type": "object",
                "properties": {
                "id": {
                "Location": "http://jsonschema.net/getweather/Location",
                "type": "string"
                },
                "type": {
                "Time": "http://jsonschema.net/getweather/Time",
                "type": "string"
                }
                },
                "required": [
                "id",
                "type"
                ]
                }
                },
                "required": [
                  "cityinfo"
                ]
                }

